pipelines:
  - name: suv_003_docker_framework_pipeline

    steps:
      - name: build_Docker_Framework
        type: DockerBuild
        configuration:
          affinityGroup:       fmkGroup
          dockerFileLocation:  framework/CI/Docker/
          dockerFileName:      jfrog-Dockerfile
          dockerImageName:     '${ArtIP}/app-docker-virtual/jfrog-docker-framework'
          dockerImageTag:      ${run_number}
          integrations:        
            - name: artifactory
            - name: app_docker_registry
          inputResources:
            - name: src_dockerfile_framework
            - name: framework_Generic_FileSpec
        execution:
          onStart:
            - 'export ArtIP=$(echo ${int_artifactory_url}|awk -F ''/'' ''{print $3}'')'
            - sed -i "s/registry/${ArtIP}/g" ${res_src_dockerfile_framework_resourcePath}/framework/CI/Docker/jfrog-Dockerfile
            - echo "Preparing for work"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "You Lose"
          onComplete: #always
            - echo "Leave it as you found it. Let's clean it"

      - name: push_Docker_Framework
        type: DockerPush
        configuration:
          affinityGroup: fmkGroup
          targetRepository: app-docker-virtual
          autoPublishBuildInfo: true
          integrations:
            - name: artifactory
          inputSteps:
            - name: build_Docker_Framework
          outputResources:
            - name: docker_Framework_BuildInfo

      - name: xray_scan_Docker_Framework_build_info
        type: Bash
        configuration:
          integrations:
            - name: artifactory
          #affinityGroup: fmkGroup
          inputResources:
            - name: docker_Framework_BuildInfo
        execution:
          onStart:
            - echo ${res_docker_Framework_BuildInfo_buildName}
            - echo ${res_docker_Framework_BuildInfo_buildNumber}
            - jfrog rt bs ${res_docker_Framework_BuildInfo_buildName} ${res_docker_Framework_BuildInfo_buildNumber} --fail=false

      - name: promoteFrameworkBuild
        type: PromoteBuild
        configuration:
          #affinityGroup: fmkGroup
          targetRepository: app-docker-release-local
          status: "DOCKER_SCAN_OK"
          comment: "Xray scan passed succesfully"
          copy: "True"
          inputSteps:
            - name: xray_scan_Docker_Framework_build_info
          inputResources:
            - name: docker_Framework_BuildInfo
          outputResources:
            - name: docker_Framework_BuildInfo_Promoted
        execution:
          onSuccess:
            - echo "Job well done!"
            - jfrog rt cp app-docker-dev-local/jfrog-docker-framework/${res_docker_Framework_BuildInfo_buildNumber}/* app-docker-release-local/jfrog-docker-framework/latest --flat=true
      